LastGamePortal/LastGamePortal/Areas/Dashboard/Models/Slider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LastGamePortal.Areas.Dashboard.Models
{
 
    public class Sliders
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }


        [Required,StringLength(20),DisplayName("Slider Başlığı")]
        public string Title { get; set; }

        [StringLength(50),DisplayName("Slider Yazısı")]
        public string Text { get; set; }
        public string Image { get; set; }
    }
}

LastGamePortal/LastGamePortal/Areas/Dashboard/Controllers/SliderController.cs
using LastGamePortal.Areas.Dashboard.Models;
using LastGamePortal.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LastGamePortal.Areas.Dashboard.Controllers
{
    [Authorize(Roles ="Yönetici")]
    public class SliderController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Dashboard/Slider
        public ActionResult Index()
        {
            ViewBag.List = db.Sliders.ToList();
            return View();
        }
        public ActionResult AddSlider(Sliders model,HttpPostedFileBase file)
        {

            
            if (Request.Files.Count > 0)
            {
                string filename = Guid.NewGuid().ToString() + ""+Request.Files[0].FileName;
                string filePath = Path.Combine(Server.MapPath("~/Content/uploads"), Path.GetFileName(filename));
                Request.Files[0].SaveAs(filePath);
                model.Image = filename;
                db.Sliders.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult RemoveSlider(int Id)
        {
            db.Sliders.Remove(db.Sliders.FirstOrDefault(m=>m.Id==Id));
            db.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

LastGamePortal/LastGamePortal/Areas/Dashboard/Views/Slider/Index.cshtml
@model LastGamePortal.Areas.Dashboard.Models.Sliders
@using LastGamePortal.Areas.Dashboard.Models
@{
    ViewBag.Title = "Slider Yönetimi";
}


<div class="row">
    <div class="col-md-10">
        <h2 class="text-muted">@ViewBag.Title</h2>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary btn-rounded" data-toggle="modal" data-target="#AddSlider">
            Yeni Slider Ekle
        </button>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Slider No </th>
                    <th scope="col">Slider Başlığı</th>
                    <th scope="col">Slider Açıklaması</th>
                    <th scope="col"></th>
    
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (Sliders item in ViewBag.List)
                    {
                        <th scope="row">@item.Id</th>
                        <td>@item.Title</td>
                        <td>@item.Text</td>
                        <td><a class="btn btn-danger btn-sm"  href="~/Dashboard/Slider/RemoveSlider?Id=@item.Id"><i class="fas fa-trash"></i> Sil</a></td>
                    }


                </tr>
           
            </tbody>
        </table>
    </div>


</div>


@using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { enctype = "multipart/form-data", id="form5" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="modal fade" id="AddSlider" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <!--Content-->
            <div class="modal-content form-elegant">
                <!--Header-->
                <div class="modal-header text-center">
                    <h3 class="modal-title w-100 dark-grey-text font-weight-bold my-3" id="myModalLabel"><strong>Slider Ekle</strong></h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!--Body-->
                <div class="modal-body mx-4">
                    <!--Body-->
                    <div class="md-form mb-5">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Slider Başlığı Gir", required = "required" })
                        @Html.LabelFor(m => m.Title, new { @class = "active" })

                    </div>
                    <div class="md-form mb-5">
                        @Html.TextBoxFor(m => m.Text, new { @class = "form-control", placeholder = "Slider Başlığı Gir", required = "required" })
                        @Html.LabelFor(m => m.Text, new { @class = "active" })
                    </div>
                    <div class="md-form">
                        <div class="file-field">
                            <div class="z-depth-1-half mb-4">
                                <img id="output" src="https://mdbootstrap.com/img/Photos/Others/placeholder.jpg" class="img-fluid"
                                     alt="example placeholder">
                            </div>
                            <div class="d-flex justify-content-center">
                                <div class="btn btn-mdb-color btn-rounded float-left">
                                    <span>Resim Seç</span>
                                    <input accept="image/*" required  onchange="readURL(this);" type="file" name="file">
                                </div>
                            </div>
                            <hr />
                        </div>
                    </div>

                    <script>
                        function readURL(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#output')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                    </script>
                    <div class="text-center mb-3">
                        <button type="submit" class="btn blue-gradient btn-block btn-rounded z-depth-1a">Kaydet</button>
                    </div>

                </div>
            </div>
            <script type="text/javascript" language=javascript>

       

            </script>
            <!--/.Content-->
        </div>
    </div>
    <!-- Modal -->



}